package vue;

import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Djurdjevic Sacha
 */
public class VueEvaluation extends VueGenerique {

    /**
     * Creates new form VueEvaluation
     */
    public VueEvaluation() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelEvaluation = new javax.swing.JPanel();
        jLabelEvaluation = new javax.swing.JLabel();
        jPanelInformation = new javax.swing.JPanel();
        jCheckBoxActiviteSportive = new javax.swing.JCheckBox();
        jCheckBoxHTA = new javax.swing.JCheckBox();
        jCheckBoxFamilleDiabete = new javax.swing.JCheckBox();
        jCheckBoxTauxGlycémie = new javax.swing.JCheckBox();
        jComboBoxAlimentation = new javax.swing.JComboBox<>();
        jTextFieldIMC = new javax.swing.JTextField();
        jTextFieldTourTaille = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxNomPatient = new javax.swing.JComboBox<>();
        jComboBoxPrenomPatient = new javax.swing.JComboBox<>();
        jLabelErrorTDC = new javax.swing.JLabel();
        jLabelErrorIMC = new javax.swing.JLabel();
        jLabelErrorPrenom = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanelEvaluation.setBackground(new java.awt.Color(51, 51, 51));

        jLabelEvaluation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEvaluation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEvaluation.setText("Nouvelle Evaluation");

        jPanelInformation.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxAlimentation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non", "Tous les jours", "Pas tous les jours" }));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nom");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Prénom");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tour de Taille (cm)");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Activité Sportive ( + 30 min )");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ATCD Traitement anti-HTA");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("ATCD familial de diabète");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("IMC (kg/m²)");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Alimentation Legumes verts");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("ATCD glycémie supérieur à la normale");

        jLabelErrorTDC.setForeground(new java.awt.Color(204, 0, 0));

        jLabelErrorIMC.setForeground(new java.awt.Color(204, 0, 0));

        jLabelErrorPrenom.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanelInformationLayout = new javax.swing.GroupLayout(jPanelInformation);
        jPanelInformation.setLayout(jPanelInformationLayout);
        jPanelInformationLayout.setHorizontalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformationLayout.createSequentialGroup()
                        .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformationLayout.createSequentialGroup()
                                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxPrenomPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxNomPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40))
                            .addGroup(jPanelInformationLayout.createSequentialGroup()
                                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTourTaille, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCheckBoxActiviteSportive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBoxHTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBoxFamilleDiabete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBoxTauxGlycémie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxAlimentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldIMC)))
                                .addContainerGap(129, Short.MAX_VALUE))))
                    .addGroup(jPanelInformationLayout.createSequentialGroup()
                        .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorTDC)
                            .addComponent(jLabelErrorIMC)
                            .addComponent(jLabelErrorPrenom))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelInformationLayout.setVerticalGroup(
            jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxNomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxPrenomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTourTaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxActiviteSportive)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxHTA)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFamilleDiabete)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAlimentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTauxGlycémie)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jLabelErrorTDC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelErrorIMC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelErrorPrenom)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButtonValider.setText("Valider");

        jButtonAnnuler.setText("Annuler");

        javax.swing.GroupLayout jPanelEvaluationLayout = new javax.swing.GroupLayout(jPanelEvaluation);
        jPanelEvaluation.setLayout(jPanelEvaluationLayout);
        jPanelEvaluationLayout.setHorizontalGroup(
            jPanelEvaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEvaluationLayout.createSequentialGroup()
                .addGroup(jPanelEvaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEvaluationLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEvaluationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEvaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonValider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelEvaluationLayout.setVerticalGroup(
            jPanelEvaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEvaluationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEvaluationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEvaluationLayout.createSequentialGroup()
                        .addComponent(jButtonValider)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAnnuler))
                    .addComponent(jPanelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEvaluation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueEvaluation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueEvaluation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueEvaluation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueEvaluation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueEvaluation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JCheckBox jCheckBoxActiviteSportive;
    private javax.swing.JCheckBox jCheckBoxFamilleDiabete;
    private javax.swing.JCheckBox jCheckBoxHTA;
    private javax.swing.JCheckBox jCheckBoxTauxGlycémie;
    private javax.swing.JComboBox<String> jComboBoxAlimentation;
    private javax.swing.JComboBox<String> jComboBoxNomPatient;
    private javax.swing.JComboBox<String> jComboBoxPrenomPatient;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelErrorIMC;
    private javax.swing.JLabel jLabelErrorPrenom;
    private javax.swing.JLabel jLabelErrorTDC;
    private javax.swing.JLabel jLabelEvaluation;
    private javax.swing.JPanel jPanelEvaluation;
    private javax.swing.JPanel jPanelInformation;
    private javax.swing.JTextField jTextFieldIMC;
    private javax.swing.JTextField jTextFieldTourTaille;
    // End of variables declaration//GEN-END:variables

    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public javax.swing.JButton getjButtonAnnuler() {
        return jButtonAnnuler;
    }

    public javax.swing.JButton getjButtonValider() {
        return jButtonValider;
    }

    public javax.swing.JCheckBox getjCheckBoxActiviteSportive() {
        return jCheckBoxActiviteSportive;
    }

    public javax.swing.JCheckBox getjCheckBoxFamilleDiabete() {
        return jCheckBoxFamilleDiabete;
    }

    public javax.swing.JCheckBox getjCheckBoxHTA() {
        return jCheckBoxHTA;
    }

    public javax.swing.JCheckBox getjCheckBoxTauxGlycémie() {
        return jCheckBoxTauxGlycémie;
    }

    public javax.swing.JComboBox<String> getjComboBoxAlimentation() {
        return jComboBoxAlimentation;
    }

    public javax.swing.JLabel getjLabelEvaluation() {
        return jLabelEvaluation;
    }

    public javax.swing.JPanel getjPanelEvaluation() {
        return jPanelEvaluation;
    }

    public javax.swing.JPanel getjPanelInformation() {
        return jPanelInformation;
    }

    public javax.swing.JTextField getjTextFieldIMC() {
        return jTextFieldIMC;
    }

    public JComboBox<String> getjComboBoxNomPatient() {
        return jComboBoxNomPatient;
    }

    public JComboBox<String> getjComboBoxPrenomPatient() {
        return jComboBoxPrenomPatient;
    }

    public javax.swing.JTextField getjTextFieldTourTaille() {
        return jTextFieldTourTaille;
    }

    public JLabel getjLabelErrorIMC() {
        return jLabelErrorIMC;
    }

    public JLabel getjLabelErrorTDC() {
        return jLabelErrorTDC;
    }

    public JLabel getjLabelErrorPrenom() {
        return jLabelErrorPrenom;
    }
    
}
