package vue;


import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class VueListeDiagnostique extends VueGenerique {

    private DefaultTableModel modeleTableListeinformation;
    private DefaultTableModel modeleTableId;
    
    /**
     * Creates new form VueListeDiagnostique
     */
    public VueListeDiagnostique() {
        super();
        initComponents();
        modeleTableListeinformation = new DefaultTableModel();
        jTableListeInformation.setModel(modeleTableListeinformation);
        
        modeleTableId = new DefaultTableModel();
        jTableId.setModel(modeleTableId);
        
;
        
    }
    
    public DefaultTableModel getModeleTableListeInformation() {
        return modeleTableListeinformation;
    }

    public JTable getjTableListeInformation() {
        return jTableListeInformation;
    }
    
    public DefaultTableModel getModeleTableId() {
        return modeleTableId;
    }

    public JTable getjTableId() {
        return jTableId;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListePersonnes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelInformationPatient = new javax.swing.JPanel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldSexe = new javax.swing.JTextField();
        jTextFieldDateNaissance = new javax.swing.JTextField();
        jTextFieldCodeSecuriteSociale = new javax.swing.JTextField();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jLabelDateNaissance = new javax.swing.JLabel();
        jLabelCodeSecuriteSociale = new javax.swing.JLabel();
        jLabelTitrePatient = new javax.swing.JLabel();
        jPanelResultatPatient = new javax.swing.JPanel();
        jTextFieldActiviteSportive = new javax.swing.JTextField();
        jTextFieldTraitement = new javax.swing.JTextField();
        jTextFieldFamillePositive = new javax.swing.JTextField();
        jTextFieldMasse = new javax.swing.JTextField();
        jTextFieldTaille = new javax.swing.JTextField();
        jTextFieldConsoLegume = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldATCDGlycemie = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldTailleScore = new javax.swing.JTextField();
        jTextFieldActiviteSportiveScore = new javax.swing.JTextField();
        jTextFieldTraitementScore = new javax.swing.JTextField();
        jTextFieldFamillePositiveScore = new javax.swing.JTextField();
        jTextFieldMassScore = new javax.swing.JTextField();
        jTextFieldConsoLegumeScore = new javax.swing.JTextField();
        jTextFieldATCDGlycemieScore = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldScoreTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldRisque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldAgeScore = new javax.swing.JTextField();
        jScrollPaneListeInformation = new javax.swing.JScrollPane();
        jTableListeInformation = new javax.swing.JTable();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jScrollPaneId = new javax.swing.JScrollPane();
        jTableId = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Liste Diagnostiques");

        jPanelInformationPatient.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jLabelNom.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNom.setText("Nom");

        jLabelPrenom.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPrenom.setText("Prenom");

        jLabelSexe.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSexe.setText("Sexe");

        jLabelDateNaissance.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDateNaissance.setText("Date de Naissance");

        jLabelCodeSecuriteSociale.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCodeSecuriteSociale.setText("Code Sécurité Sociale");

        jLabelTitrePatient.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitrePatient.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitrePatient.setText("Information du Patient");

        javax.swing.GroupLayout jPanelInformationPatientLayout = new javax.swing.GroupLayout(jPanelInformationPatient);
        jPanelInformationPatient.setLayout(jPanelInformationPatientLayout);
        jPanelInformationPatientLayout.setHorizontalGroup(
            jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTitrePatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addGroup(jPanelInformationPatientLayout.createSequentialGroup()
                        .addGroup(jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelInformationPatientLayout.createSequentialGroup()
                                .addComponent(jLabelNom)
                                .addGap(125, 125, 125))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInformationPatientLayout.createSequentialGroup()
                                .addGroup(jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelSexe, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDateNaissance, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodeSecuriteSociale, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPrenom, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNom)
                            .addComponent(jTextFieldPrenom)
                            .addComponent(jTextFieldSexe)
                            .addComponent(jTextFieldDateNaissance)
                            .addComponent(jTextFieldCodeSecuriteSociale, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInformationPatientLayout.setVerticalGroup(
            jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformationPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitrePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSexe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateNaissance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInformationPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodeSecuriteSociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodeSecuriteSociale))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelResultatPatient.setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldTaille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTailleActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tour de taille (cm)");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Activités physique (30 min/j)");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ATCD de traîtement anti-HTA");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("ATCD familial de diabète");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("IMC (kg/m²)");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Part des léhumes dans l'alimentation");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("ATCD de glycémie supérieure à la normale");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Résultat du patient");

        jTextFieldMassScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMassScoreActionPerformed(evt);
            }
        });

        jTextFieldATCDGlycemieScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldATCDGlycemieScoreActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Calcul du score de risque de diabète dans les 10 ans");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Risque en %");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Age");

        javax.swing.GroupLayout jPanelResultatPatientLayout = new javax.swing.GroupLayout(jPanelResultatPatient);
        jPanelResultatPatient.setLayout(jPanelResultatPatientLayout);
        jPanelResultatPatientLayout.setHorizontalGroup(
            jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultatPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelResultatPatientLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldScoreTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRisque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultatPatientLayout.createSequentialGroup()
                        .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelResultatPatientLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(236, 236, 236)
                                .addComponent(jTextFieldAge)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAgeScore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelResultatPatientLayout.createSequentialGroup()
                                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTaille)
                                    .addComponent(jTextFieldActiviteSportive)
                                    .addComponent(jTextFieldTraitement)
                                    .addComponent(jTextFieldFamillePositive)
                                    .addComponent(jTextFieldConsoLegume)
                                    .addComponent(jTextFieldMasse)
                                    .addComponent(jTextFieldATCDGlycemie, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldConsoLegumeScore)
                                    .addComponent(jTextFieldMassScore)
                                    .addComponent(jTextFieldFamillePositiveScore)
                                    .addComponent(jTextFieldATCDGlycemieScore)
                                    .addComponent(jTextFieldTailleScore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldActiviteSportiveScore)
                                    .addComponent(jTextFieldTraitementScore))))
                        .addGap(426, 426, 426)))
                .addContainerGap())
        );
        jPanelResultatPatientLayout.setVerticalGroup(
            jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultatPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldTailleScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldActiviteSportive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldActiviteSportiveScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTraitement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTraitementScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFamillePositive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldFamillePositiveScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldMassScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConsoLegume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldConsoLegumeScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldATCDGlycemie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldATCDGlycemieScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAgeScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanelResultatPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldScoreTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldRisque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableListeInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListeInformation.setEnabled(false);
        jTableListeInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListeInformationMouseClicked(evt);
            }
        });
        jScrollPaneListeInformation.setViewportView(jTableListeInformation);

        jButtonModifier.setText("Modifier diagnostique");

        jButtonSupprimer.setText("Supprimer diagnostique");

        jButtonRetour.setText("Retour");

        jTableId.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPaneId.setViewportView(jTableId);

        javax.swing.GroupLayout jPanelListePersonnesLayout = new javax.swing.GroupLayout(jPanelListePersonnes);
        jPanelListePersonnes.setLayout(jPanelListePersonnesLayout);
        jPanelListePersonnesLayout.setHorizontalGroup(
            jPanelListePersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListePersonnesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListePersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelListePersonnesLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelListePersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelListePersonnesLayout.createSequentialGroup()
                                .addComponent(jButtonModifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSupprimer)
                                .addGap(680, 680, 680)
                                .addComponent(jButtonRetour)))))
                .addGap(0, 188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListePersonnesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneListeInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelListePersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelInformationPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResultatPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelListePersonnesLayout.setVerticalGroup(
            jPanelListePersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListePersonnesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanelListePersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListePersonnesLayout.createSequentialGroup()
                        .addComponent(jPanelInformationPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelResultatPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneListeInformation)
                    .addComponent(jScrollPaneId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelListePersonnesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer)
                    .addComponent(jButtonRetour))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListePersonnes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListePersonnes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jTextFieldTailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTailleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTailleActionPerformed

    private void jTextFieldMassScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMassScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMassScoreActionPerformed

    private void jTextFieldATCDGlycemieScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldATCDGlycemieScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldATCDGlycemieScoreActionPerformed

    private void jTableListeInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListeInformationMouseClicked

    }//GEN-LAST:event_jTableListeInformationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueListeDiagnostique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueListeDiagnostique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueListeDiagnostique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueListeDiagnostique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueListeDiagnostique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodeSecuriteSociale;
    private javax.swing.JLabel jLabelDateNaissance;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JLabel jLabelTitrePatient;
    private javax.swing.JPanel jPanelInformationPatient;
    private javax.swing.JPanel jPanelListePersonnes;
    private javax.swing.JPanel jPanelResultatPatient;
    private javax.swing.JScrollPane jScrollPaneId;
    private javax.swing.JScrollPane jScrollPaneListeInformation;
    private javax.swing.JTable jTableId;
    private javax.swing.JTable jTableListeInformation;
    private javax.swing.JTextField jTextFieldATCDGlycemie;
    private javax.swing.JTextField jTextFieldATCDGlycemieScore;
    private javax.swing.JTextField jTextFieldActiviteSportive;
    private javax.swing.JTextField jTextFieldActiviteSportiveScore;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldAgeScore;
    private javax.swing.JTextField jTextFieldCodeSecuriteSociale;
    private javax.swing.JTextField jTextFieldConsoLegume;
    private javax.swing.JTextField jTextFieldConsoLegumeScore;
    private javax.swing.JTextField jTextFieldDateNaissance;
    private javax.swing.JTextField jTextFieldFamillePositive;
    private javax.swing.JTextField jTextFieldFamillePositiveScore;
    private javax.swing.JTextField jTextFieldMassScore;
    private javax.swing.JTextField jTextFieldMasse;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldRisque;
    private javax.swing.JTextField jTextFieldScoreTotal;
    private javax.swing.JTextField jTextFieldSexe;
    private javax.swing.JTextField jTextFieldTaille;
    private javax.swing.JTextField jTextFieldTailleScore;
    private javax.swing.JTextField jTextFieldTraitement;
    private javax.swing.JTextField jTextFieldTraitementScore;
    // End of variables declaration//GEN-END:variables

    
    
    public javax.swing.JButton getjButtonModifier() {
        return jButtonModifier;
    }

    public javax.swing.JButton getjButtonRetour() {
        return jButtonRetour;
    }

    public javax.swing.JButton getjButtonSupprimer() {
        return jButtonSupprimer;
    }

    public javax.swing.JTextField getjTextFieldATCDGlycemie() {
        return jTextFieldATCDGlycemie;
    }

    public javax.swing.JTextField getjTextFieldATCDGlycemieScore() {
        return jTextFieldATCDGlycemieScore;
    }

    public javax.swing.JTextField getjTextFieldActiviteSportive() {
        return jTextFieldActiviteSportive;
    }

    public javax.swing.JTextField getjTextFieldActiviteSportiveScore() {
        return jTextFieldActiviteSportiveScore;
    }

    public javax.swing.JTextField getjTextFieldCodeSecuriteSociale() {
        return jTextFieldCodeSecuriteSociale;
    }

    public javax.swing.JTextField getjTextFieldConsoLegume() {
        return jTextFieldConsoLegume;
    }

    public javax.swing.JTextField getjTextFieldConsoLegumeScore() {
        return jTextFieldConsoLegumeScore;
    }

    public javax.swing.JTextField getjTextFieldDateNaissance() {
        return jTextFieldDateNaissance;
    }

    public javax.swing.JTextField getjTextFieldFamillePositive() {
        return jTextFieldFamillePositive;
    }

    public javax.swing.JTextField getjTextFieldFamillePositiveScore() {
        return jTextFieldFamillePositiveScore;
    }

    public javax.swing.JTextField getjTextFieldMassScore() {
        return jTextFieldMassScore;
    }

    public javax.swing.JTextField getjTextFieldMasse() {
        return jTextFieldMasse;
    }

    public javax.swing.JTextField getjTextFieldNom() {
        return jTextFieldNom;
    }

    public javax.swing.JTextField getjTextFieldPrenom() {
        return jTextFieldPrenom;
    }

    public javax.swing.JTextField getjTextFieldRisque() {
        return jTextFieldRisque;
    }

    public javax.swing.JTextField getjTextFieldScoreTotal() {
        return jTextFieldScoreTotal;
    }

    public javax.swing.JTextField getjTextFieldSexe() {
        return jTextFieldSexe;
    }

    public javax.swing.JTextField getjTextFieldTaille() {
        return jTextFieldTaille;
    }

    public javax.swing.JTextField getjTextFieldTailleScore() {
        return jTextFieldTailleScore;
    }

    public javax.swing.JTextField getjTextFieldTraitement() {
        return jTextFieldTraitement;
    }

    public JTextField getjTextFieldAge() {
        return jTextFieldAge;
    }

    public JTextField getjTextFieldAgeScore() {
        return jTextFieldAgeScore;
    }

    public javax.swing.JTextField getjTextFieldTraitementScore() {
        return jTextFieldTraitementScore;
    }
}
