package vue;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Djurdjevic Sacha
 */
public class VueStatistique extends VueGenerique {

    /**
     * Creates new form VueStatistique
     */
    public VueStatistique() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelTitreMain = new javax.swing.JLabel();
        jPanelChoixSexe = new javax.swing.JPanel();
        jLabelTitreSexe = new javax.swing.JLabel();
        jLabeltitreAge = new javax.swing.JLabel();
        jLabelTitreDescription = new javax.swing.JLabel();
        jComboBoxAge = new javax.swing.JComboBox<>();
        jComboBoxSexe = new javax.swing.JComboBox<>();
        jComboBoxSelectionStat = new javax.swing.JComboBox<>();
        jButtonValider = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jPanelStatistique = new javax.swing.JPanel();
        jPanelStatistiquePrincipale = new javax.swing.JPanel();
        jLabelStat1 = new javax.swing.JLabel();
        jLabelStat2 = new javax.swing.JLabel();
        jLabelStat3 = new javax.swing.JLabel();
        jLabelStat4 = new javax.swing.JLabel();
        jLabelStat5 = new javax.swing.JLabel();
        jTextFieldStat1 = new javax.swing.JTextField();
        jTextFieldStat2 = new javax.swing.JTextField();
        jTextFieldStat4 = new javax.swing.JTextField();
        jTextFieldStat5 = new javax.swing.JTextField();
        jTextFieldStat3 = new javax.swing.JTextField();
        jPanelMoyenne = new javax.swing.JPanel();
        jLabelMoyenne = new javax.swing.JLabel();
        jTextFieldStatMoyenne = new javax.swing.JTextField();
        jTextFieldStatNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelStatistiqueTitre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanelMain.setBackground(new java.awt.Color(51, 51, 51));
        jPanelMain.setForeground(new java.awt.Color(51, 51, 51));

        jLabelTitreMain.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitreMain.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitreMain.setText("Statistique - Choix Descriptifs");

        jPanelChoixSexe.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitreSexe.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitreSexe.setText("Choix des sexes");

        jLabeltitreAge.setForeground(new java.awt.Color(0, 0, 0));
        jLabeltitreAge.setText("Choix tranche d'age");

        jLabelTitreDescription.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitreDescription.setText("Choix des descriptions");

        jComboBoxAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moins de 45 ans", "Entre 45 et 54 ans", "Entre 54 et 64 ans", "Plus de 64 ans" }));

        jComboBoxSexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tous", "Femmes", "Hommes" }));

        jComboBoxSelectionStat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tous", "Tour de Taille", "Activite physique", "Antécédent de traitement anti-HTA", "Antécédent familial de diabète", "IMC", "Part des légumes verts dans l'alimentation", "Antécédent de glycémie supérieur à la normale" }));

        javax.swing.GroupLayout jPanelChoixSexeLayout = new javax.swing.GroupLayout(jPanelChoixSexe);
        jPanelChoixSexe.setLayout(jPanelChoixSexeLayout);
        jPanelChoixSexeLayout.setHorizontalGroup(
            jPanelChoixSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChoixSexeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelChoixSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitreSexe)
                    .addComponent(jComboBoxSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltitreAge)
                    .addComponent(jLabelTitreDescription)
                    .addComponent(jComboBoxSelectionStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelChoixSexeLayout.setVerticalGroup(
            jPanelChoixSexeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChoixSexeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreSexe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltitreAge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTitreDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxSelectionStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButtonValider.setText("Regarder Statistique");

        jButtonRetour.setText("Retour");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonValider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRetour)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelChoixSexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreMain)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChoixSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValider)
                    .addComponent(jButtonRetour))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelStatistique.setBackground(new java.awt.Color(51, 51, 51));
        jPanelStatistique.setForeground(new java.awt.Color(51, 51, 51));

        jPanelStatistiquePrincipale.setBackground(new java.awt.Color(255, 255, 255));

        jLabelStat1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStat1.setText("jLabel1");

        jLabelStat2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStat2.setText("jLabel2");

        jLabelStat3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStat3.setText("jLabel3");

        jLabelStat4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStat4.setText("jLabel4");

        jLabelStat5.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStat5.setText("jLabel5");

        jTextFieldStat1.setEnabled(false);

        jTextFieldStat2.setEnabled(false);

        jTextFieldStat4.setEnabled(false);

        jTextFieldStat5.setEnabled(false);

        jTextFieldStat3.setEnabled(false);

        jPanelMoyenne.setBackground(new java.awt.Color(204, 204, 204));

        jLabelMoyenne.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMoyenne.setText("Moyenne");

        jTextFieldStatMoyenne.setEnabled(false);

        jTextFieldStatNombre.setEnabled(false);

        jLabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setText("Echantillon Total");

        javax.swing.GroupLayout jPanelMoyenneLayout = new javax.swing.GroupLayout(jPanelMoyenne);
        jPanelMoyenne.setLayout(jPanelMoyenneLayout);
        jPanelMoyenneLayout.setHorizontalGroup(
            jPanelMoyenneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoyenneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMoyenneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMoyenneLayout.createSequentialGroup()
                        .addComponent(jTextFieldStatMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMoyenne))
                    .addGroup(jPanelMoyenneLayout.createSequentialGroup()
                        .addComponent(jTextFieldStatNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombre)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanelMoyenneLayout.setVerticalGroup(
            jPanelMoyenneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoyenneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMoyenneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStatMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMoyenne))
                .addGap(18, 18, 18)
                .addGroup(jPanelMoyenneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStatNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelStatistiquePrincipaleLayout = new javax.swing.GroupLayout(jPanelStatistiquePrincipale);
        jPanelStatistiquePrincipale.setLayout(jPanelStatistiquePrincipaleLayout);
        jPanelStatistiquePrincipaleLayout.setHorizontalGroup(
            jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatistiquePrincipaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldStat5, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jTextFieldStat4)
                    .addComponent(jTextFieldStat3)
                    .addComponent(jTextFieldStat2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldStat1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStat2)
                            .addComponent(jLabelStat1)
                            .addComponent(jLabelStat3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabelStat4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabelStat5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(jPanelMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelStatistiquePrincipaleLayout.setVerticalGroup(
            jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatistiquePrincipaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelStatistiquePrincipaleLayout.createSequentialGroup()
                        .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStat1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStat2)
                            .addComponent(jTextFieldStat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStat3)
                            .addComponent(jTextFieldStat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStat4)
                            .addComponent(jTextFieldStat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelStatistiquePrincipaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStat5)
                            .addComponent(jTextFieldStat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jLabelStatistiqueTitre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelStatistiqueTitre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatistiqueTitre.setText("TITRE");

        javax.swing.GroupLayout jPanelStatistiqueLayout = new javax.swing.GroupLayout(jPanelStatistique);
        jPanelStatistique.setLayout(jPanelStatistiqueLayout);
        jPanelStatistiqueLayout.setHorizontalGroup(
            jPanelStatistiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatistiqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatistiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelStatistiquePrincipale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatistiqueTitre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStatistiqueLayout.setVerticalGroup(
            jPanelStatistiqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatistiqueLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabelStatistiqueTitre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelStatistiquePrincipale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelStatistique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelStatistique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueStatistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueStatistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueStatistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueStatistique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueStatistique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox<String> jComboBoxAge;
    private javax.swing.JComboBox<String> jComboBoxSelectionStat;
    private javax.swing.JComboBox<String> jComboBoxSexe;
    private javax.swing.JLabel jLabelMoyenne;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelStat1;
    private javax.swing.JLabel jLabelStat2;
    private javax.swing.JLabel jLabelStat3;
    private javax.swing.JLabel jLabelStat4;
    private javax.swing.JLabel jLabelStat5;
    private javax.swing.JLabel jLabelStatistiqueTitre;
    private javax.swing.JLabel jLabelTitreDescription;
    private javax.swing.JLabel jLabelTitreMain;
    private javax.swing.JLabel jLabelTitreSexe;
    private javax.swing.JLabel jLabeltitreAge;
    private javax.swing.JPanel jPanelChoixSexe;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMoyenne;
    private javax.swing.JPanel jPanelStatistique;
    private javax.swing.JPanel jPanelStatistiquePrincipale;
    private javax.swing.JTextField jTextFieldStat1;
    private javax.swing.JTextField jTextFieldStat2;
    private javax.swing.JTextField jTextFieldStat3;
    private javax.swing.JTextField jTextFieldStat4;
    private javax.swing.JTextField jTextFieldStat5;
    private javax.swing.JTextField jTextFieldStatMoyenne;
    private javax.swing.JTextField jTextFieldStatNombre;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonRetour() {
        return jButtonRetour;
    }

    public JButton getjButtonValider() {
        return jButtonValider;
    }

    public JPanel getjPanelStatistique() {
        return jPanelStatistique;
    }

    public JComboBox<String> getjComboBoxAge() {
        return jComboBoxAge;
    }

    public JComboBox<String> getjComboBoxSelectionStat() {
        return jComboBoxSelectionStat;
    }

    public JComboBox<String> getjComboBoxSexe() {
        return jComboBoxSexe;
    }

    public JLabel getjLabelStat1() {
        return jLabelStat1;
    }

    public JLabel getjLabelStat2() {
        return jLabelStat2;
    }

    public JLabel getjLabelStat3() {
        return jLabelStat3;
    }

    public JLabel getjLabelStat4() {
        return jLabelStat4;
    }

    public JLabel getjLabelStat5() {
        return jLabelStat5;
    }

    public JLabel getjLabelStatistiqueTitre() {
        return jLabelStatistiqueTitre;
    }

    public JTextField getjTextFieldStat1() {
        return jTextFieldStat1;
    }

    public JTextField getjTextFieldStat2() {
        return jTextFieldStat2;
    }

    public JTextField getjTextFieldStat3() {
        return jTextFieldStat3;
    }

    public JTextField getjTextFieldStat4() {
        return jTextFieldStat4;
    }

    public JTextField getjTextFieldStat5() {
        return jTextFieldStat5;
    }

    public JTextField getjTextFieldStatMoyenne() {
        return jTextFieldStatMoyenne;
    }

    public JTextField getjTextFieldStatNombre() {
        return jTextFieldStatNombre;
    }
}
